# SPDX-License-Identifier: GPL-3.0-only

board-y += board.c
board-y += gpio.c

EC = ite
CONFIG_EC_ITE_IT5570E = y
CONFIG_EC_FLASH_SIZE_128K = y

# Intel-based host
CONFIG_PLATFORM_INTEL = y
CONFIG_BUS_ESPI = y

# Enable firmware security
CONFIG_SECURITY = y

# Include keyboard
KEYBOARD = 15in_102

# Set keyboard LED mechanism
CONFIG_HAVE_KBLED = y
CONFIG_KBLED = rgb_pwm

# Set battery I2C bus
CONFIG_I2C_SMBUS = I2C_4

# Set touchpad PS2 bus
CONFIG_PS2_TOUCHPAD = PS2_3

# Set smart charger parameters
# TODO: actually bq24800
# FIXME: Verify parts and values.
CONFIG_CHARGER = bq24780s
CONFIG_CHARGER_ADAPTER_RSENSE = 5
CONFIG_CHARGER_BATTERY_RSENSE = 10
CONFIG_CHARGER_CHARGE_CURRENT = 2048
CONFIG_CHARGER_CHARGE_VOLTAGE = 13050
CONFIG_CHARGER_INPUT_CURRENT = 11500

# Set CPU power limits in watts
CONFIG_POWER_LIMIT_AC = 180
CONFIG_POWER_LIMIT_DC = 45

# Enable dGPU support
CONFIG_DRIVERS_DGPU_NVIDIA = y

# Fan configs
CONFIG_FAN1_PWM = DCR2
CONFIG_FAN1_POINTS = " \
	FAN_POINT(50, 40), \
	FAN_POINT(55, 40), \
	FAN_POINT(60, 55), \
	FAN_POINT(69, 55), \
	FAN_POINT(74, 68), \
	FAN_POINT(79, 68), \
	FAN_POINT(80, 72), \
	FAN_POINT(87, 100), \
"

CONFIG_FAN2_PWM = DCR4
CONFIG_FAN2_POINTS = " \
	FAN_POINT(50, 40), \
	FAN_POINT(56, 40), \
	FAN_POINT(72, 100), \
"
