# SPDX-License-Identifier: GPL-3.0-only

board-y += board.c
board-y += gpio.c

CONFIG_SOC_ITE_IT5570E = y
CONFIG_SOC_FLASH_SIZE_128K = y

# Intel-based host
CONFIG_PLATFORM_INTEL = y
CONFIG_BUS_ESPI = y
CONFIG_PECI_OVER_ESPI = y

# Enable firmware security
CONFIG_SECURITY = y

# Include keyboard
KEYBOARD = 18H9LHA04

# Set keyboard LED mechanism
CONFIG_HAVE_KBLED = y
CONFIG_KBLED = rgb_pwm

# Set battery I2C bus
CONFIG_I2C_SMBUS = I2C_4

# Set touchpad PS2 bus
CONFIG_PS2_TOUCHPAD = PS2_3

# Set smart charger parameters
# TODO: actually bq24800
CONFIG_CHARGER = bq24780s
CONFIG_CHARGER_ADAPTER_RSENSE = 10
CONFIG_CHARGER_BATTERY_RSENSE = 10
CONFIG_CHARGER_CHARGE_CURRENT = 3072
CONFIG_CHARGER_CHARGE_VOLTAGE = 17600
CONFIG_CHARGER_INPUT_CURRENT = 11500

# Set USB-PD parameters
CONFIG_HAVE_USBPD = y
CONFIG_USBPD_TPS65987 = y
CONFIG_I2C_USBPD = I2C_1

# Set CPU power limits in watts
CONFIG_POWER_LIMIT_AC = 230
CONFIG_POWER_LIMIT_DC = 55

# Enable dGPU support
CONFIG_HAVE_DGPU = y
CONFIG_I2C_DGPU = I2C_1

# Fan configs
CONFIG_FAN1_PWM = DCR2
CONFIG_FAN1_PWM_MIN = 28
CONFIG_FAN1_POINTS = " \
	FAN_POINT(60, 28), \
	FAN_POINT(65, 28), \
	FAN_POINT(70, 40), \
	FAN_POINT(75, 60), \
	FAN_POINT(80, 75), \
	FAN_POINT(85, 90), \
	FAN_POINT(90, 100), \
"

CONFIG_FAN2_PWM = DCR4
CONFIG_FAN2_PWM_MIN = 28
CONFIG_FAN2_POINTS = " \
	FAN_POINT(60, 28), \
	FAN_POINT(65, 28), \
	FAN_POINT(70, 40), \
	FAN_POINT(75, 60), \
	FAN_POINT(80, 75), \
	FAN_POINT(85, 90), \
	FAN_POINT(90, 100), \
"
