# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: NONE

# A container for Small Device C Compiler based on Debian
# SDCC: https://sdcc.sourceforge.net/

ARG CONTAINER_IMAGE="debian:12.5"

FROM ${CONTAINER_IMAGE} as sdcc-build
ARG SDCC_REPO
ARG SDCC_REV
ARG SDCC_VERSION
WORKDIR /tmp

RUN apt-get --quiet update && \
    apt-get --quiet install --no-install-recommends --assume-yes \
        autoconf \
        automake \
        bison \
        ca-certificates \
        flex \
        g++ \
        gcc \
        gputils \
        libboost-dev \
        make \
        subversion \
        zlib1g-dev \
    && apt-get clean

RUN svn checkout \
        --depth infinity \
        --revision ${SDCC_REV} \
        ${SDCC_REPO}/tags/sdcc-${SDCC_VERSION}/sdcc \
        sdcc

# Only the MCS-51 port is needed.
RUN cd sdcc && \
    sh ./configure \
        --disable-z80-port \
        --disable-z180-port \
        --disable-r2k-port \
        --disable-r2ka-port \
        --disable-r3ka-port \
        --disable-sm83-port \
        --disable-tlcs90-port \
        --disable-ez80_z80-port \
        --disable-z80n-port \
        --disable-ds390-port \
        --disable-ds400-port \
        --disable-pic14-port \
        --disable-pic16-port \
        --disable-hc08-port \
        --disable-s08-port \
        --disable-stm8-port \
        --disable-pdk13-port \
        --disable-pdk14-port \
        --disable-pdk15-port \
        --disable-mos6502-port \
        --disable-ucsim \
        --disable-sdcdb \
        --disable-non-free \
        --prefix= && \
    make -j $(nproc) && \
    make install DESTDIR=/opt/sdcc

FROM ${CONTAINER_IMAGE}
ARG SDCC_REV
ARG SDCC_VERSION
COPY --from=sdcc-build /opt/sdcc /opt/sdcc
ENV SDCC_REV "${SDCC_REV}"
ENV SDCC_VERSION "${SDCC_VERSION}"
ENV SDCC_PATH "/opt/sdcc"
ENV PATH "${SDCC_PATH}/bin:$PATH"

RUN apt-get --quiet update && \
    apt-get --quiet install --no-install-recommends --assume-yes \
        bash \
        binutils \
        git \
        make \
        xxd \
    && apt-get clean

WORKDIR /workspace
CMD ["bash"]
