# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: NONE

version = 1

[[annotations]]
path = ["Cargo.lock"]
precedence = "override"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "NONE"
