# SPDX-License-Identifier: GPL-3.0-only

board-y += board.c
board-y += gpio.c

EC = ite
CONFIG_EC_ITE_IT5570E = y
CONFIG_EC_FLASH_SIZE_256K = y

# Enable eSPI
CONFIG_BUS_ESPI = y
CONFIG_PECI_OVER_ESPI = y

# Enable firmware security
#CONFIG_SECURITY = y

# Set keyboard configs
KEYBOARD = 18H9LHA04
KBLED = rgb_pwm

# Set touchpad PS2 bus
CFLAGS += -DPS2_TOUCHPAD=PS2_3

# Set smart charger parameters
CHARGER = oz26786
CFLAGS += -DI2C_SMBUS=I2C_4
CFLAGS += \
	-DCHARGER_ADAPTER_RSENSE=5 \
	-DCHARGER_BATTERY_RSENSE=10 \
	-DCHARGER_CHARGE_CURRENT=3072 \
	-DCHARGER_CHARGE_VOLTAGE=17400 \
	-DCHARGER_INPUT_CURRENT=11500

# Set CPU power limits in watts
CFLAGS += \
	-DPOWER_LIMIT_AC=230 \
	-DPOWER_LIMIT_DC=45

# Custom fan curve
CFLAGS += -DBOARD_HEATUP=5
CFLAGS += -DBOARD_COOLDOWN=20
CFLAGS += -DBOARD_FAN_POINTS="\
	FAN_POINT(50, 28), \
	FAN_POINT(55, 28), \
	FAN_POINT(60, 40), \
	FAN_POINT(65, 60), \
	FAN_POINT(70, 75), \
	FAN_POINT(75, 90), \
	FAN_POINT(80, 100) \
"

# Enable DGPU support
CFLAGS += -DHAVE_DGPU=1
CFLAGS += -DI2C_DGPU=I2C_1
CFLAGS += -DBOARD_DGPU_HEATUP=5
CFLAGS += -DBOARD_DGPU_COOLDOWN=20
CFLAGS += -DBOARD_DGPU_FAN_POINTS="\
	FAN_POINT(50, 28), \
	FAN_POINT(55, 28), \
	FAN_POINT(60, 40), \
	FAN_POINT(65, 60), \
	FAN_POINT(70, 75), \
	FAN_POINT(75, 90), \
	FAN_POINT(80, 100) \
"

# Add system76 common code
include src/board/system76/common/common.mk
