# SPDX-License-Identifier: GPL-3.0-only

ifneq ($(CONFIG_FAN1_PWM),)
CFLAGS += -DFAN1_PWM=$(CONFIG_FAN1_PWM)
ifneq ($(CONFIG_FAN1_PWM_MIN),)
CFLAGS += -DFAN1_PWM_MIN=$(CONFIG_FAN1_PWM_MIN)
endif
CFLAGS += -DBOARD_FAN1_POINTS=$(CONFIG_FAN1_POINTS)
endif

ifneq ($(CONFIG_FAN2_PWM),)
CFLAGS += -DFAN2_PWM=$(CONFIG_FAN2_PWM)
ifneq ($(CONFIG_FAN2_PWM_MIN),)
CFLAGS += -DFAN2_PWM_MIN=$(CONFIG_FAN2_PWM_MIN)
endif
CFLAGS += -DBOARD_FAN2_POINTS=$(CONFIG_FAN2_POINTS)
endif

#CONFIG_FAN_CTRL_INTERP = y
CONFIG_FAN_CTRL_STEP = y

ifeq ($(CONFIG_FAN_CTRL_INTERP),y)
CFLAGS += -DCONFIG_FAN_CTRL_INTERP=1
app-y += fan/interp.c
else ifeq ($(CONFIG_FAN_CTRL_STEP),y)
CFLAGS += -DCONFIG_FAN_CTRL_STEP=1
app-y += fan/step.c
endif
