# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: NONE

# A container for System76 EC development.

ARG CONTAINER_IMAGE="docker.io/library/debian:trixie-20260713-slim@sha256:53dfdbcd6fbc78c5052f35d2a5c798259f4c615cd93582b4ff5ad4f04249c7e3"

ARG RUST_TOOLCHAIN="1.85.0"

FROM ${CONTAINER_IMAGE}
ARG RUST_TOOLCHAIN

RUN apt-get --quiet update \
    && apt-get --quiet install --no-install-recommends --assume-yes \
        bash \
        binutils \
        ca-certificates \
        gcc \
        git \
        libc6-dev \
        libhidapi-dev \
        libstdc++6 \
        make \
        pkgconf \
        reuse \
        rustup \
        sdcc \
        shellcheck \
        uncrustify \
        xxd \
    && apt-get clean

# XXX: rustup 1.27 does not recognize toolchain if preceding option specifies
# a comma separated list as an argument with a space.
# Ref: https://github.com/rust-lang/rustup/issues/4073
RUN rustup toolchain install \
        --target x86_64-unknown-linux-gnu,x86_64-unknown-uefi \
        --profile minimal \
        --component=clippy,rustfmt \
        ${RUST_TOOLCHAIN}

WORKDIR /workspace
CMD ["bash"]
