# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: 2026 System76, Inc.

set(CMAKE_SYSTEM_NAME "Generic")
set(CMAKE_SYSTEM_VERSION "0")
set(CMAKE_SYSTEM_PROCESSOR "mcs51")

# On Fedora, SDCC programs are prefixed with `sdcc-`.
find_program(SDCC_EXE NAMES sdcc sdcc-sdcc REQUIRED)
find_program(SDAS_EXE NAMES sdas8051 sdcc-sdas8051 REQUIRED)

set(CMAKE_C_COMPILER ${SDCC_EXE})
set(CMAKE_ASM_COMPILER ${SDAS_EXE})

set(CMAKE_C_COMPILER_WORKS TRUE CACHE BOOL "" FORCE)
set(CMAKE_ASM_COMPILER_WORKS TRUE CACHE BOOL "" FORCE)

#set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
#set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
